ESP32_STREAM_URL = "http://192.168.137.159:81/stream"
IDENTIFY_THREASHOLD = 0.5
FACE_DETECTION_SIZE = (640, 640)

KEY_PERMISSIONS = "PERMISSIONS"

KEY_NAME = "NAME"
KEY_ID = "ID"
KEY_PW = "PW"
KEY_EMAIL = "EMAIL"
KEY_PHONE = "PHONE"

KEY_REG_DATE = "REG_DATE"
KEY_MOT_DATE = "MOT_DATE"

KEY_IS_APPROVE = "IS_APPROVE"
KEY_PERMISSIONS = "PERMISSIONS"
KEY_SENIOR_ID = "SENIOR_ID"

KEY_IS_FIRST_LOGIN = "IS_FIRST_LOGIN"

DELETED_ID_FILE = "deleted_id.json"
