FACES_DIR = "app/domains/stream/registered_faces"
ESP32_STREAM_URL = "http://192.168.137.159:81/stream"
KEY_PERMISSIONS = "PERMISSIONS"

KEY_ID = "ID"
KEY_PW = "PW"
KEY_EMAIL = "EMAIL"
KEY_PHONE = "PHONE"

KEY_REG_DATE = "REG_DATE"
KEY_MOT_DATE = "MOT_DATE"

KEY_IS_APPROVE = "IS_APPROVE"
KEY_PERMISSIONS = "PERMISSIONS"
KEY_SENIOR_ID = "SENIOR_ID"

DELETED_ID_FILE = "deleted_id.json"
